### ISSUE TITLE
Completion date: Optional or not?

### ISSUE THREAD

**Issue by PiCT0** [todotxt/todo.txt#26]
The [illustration of the `todo.txt` format](../blob/b5c5f5ca/description.png) states

> Optional - Completion Date

while the [definition of the format for complete tasks](../blob/b5c5f5ca/todo.txt) states that the completion date is required:

> With the **completed date (required)**, if you've used the prepended date (optional), you can calculate how many days it took to complete a task.

Therefore, is the "Optional" supposed to mean "depending on the completion status of the task" or is this a discrepancy? In particular, can a complete task omit its completion date?

**Comment by davidstosik** [comment]
Two more lines that makes things confusing (emphasis mine):

> Optional -- Creation date (**must** be specified if completion date is)

> **If** you’ve prepended the creation date to your task, on completion it will appear directly after the completion date.

So far we have:
- creation date is optional
- completion date must be provided when the task is completed (`x`)
- creation date must be provided when the completed was

Now, what happens when I complete the task `call mom` (nothing more on the todo.txt line, especially no creation date, as it is optional)?
1. Completed date is required, so I need to add it: `x 2019-07-03 call mom`.
2. But now, as completion date is provided creation date must be specified too, but I don't have it! `x 2019-07-03 ????-??-?? call mom`

My take, which does not perfectly match the spec (no logical interpretation can):
- start date is optional (_never_ required)
- completion date does not make sense for incomplete tasks
- completion date is required on completed tasks
- start date may stick to completed tasks

## Valid ✅ 
- `2019-07-01 call mom`: the provided date is the creation date
- `x 2019-07-03 call mom`: the provided date is the completion date
- `x 2019-07-03 2019-07-01 call mom`: the provided dates are, in order, completion then creation

## Invalid ❌ 
- `2019-07-03 2019-07-01 call mom`: the task is incomplete, can't have a completion date
- `x call mom`: a completed task needs _at least_ a completion date
